services:
  #playlimana:
  #  container_name: playlimana
  #  build: .
  #  security_opt:
  #      - seccomp:unconfined
  #  ports:
  #    - "9000:9000"
  #  env_file:
  #    - .env
  #  environment:
  #    - Machine=DEV
  #    - FRONTEND_URL=${FRONTEND_URL}
  #    - QUARKUS_HTTP_PORT=9000
  #    - QUARKUS_OPENTELEMETRY_ENABLED=true
  #    - QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
  #    - QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_PROTOCOL=grpc
  #  networks:
  #    - playlimana_net
  #  depends_on:
  #    playlimana-db:
  #      condition: service_started

  playlimana-db:
    container_name: playlimana-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hibernate
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: hibernate_db
    volumes:
      - data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
        - playlimana_net

volumes:
  data:

networks:
  playlimana_net:
    name: playlimana_net
    external: true