global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'quarkus-app'
    static_configs:
      - targets: ['playlimana:9000']
        labels:
          group: 'quarkus'
